[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
authors = ["Jonas Everaert"]

[dependencies]
parser = { path = "../parser" }

[build-dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
